apiVersion: v1 # versão da API do Kubernetes
kind: PersistentVolumeClaim # tipo de recurso, no caso, um PersistentVolumeClaim
metadata: # metadados do recurso
  name: meu-pvc # nome do PVC
spec: # especificação do PVC
  accessModes: # modo de acesso ao volume
    - ReadWriteOnce # modo de acesso RWO, ou seja, somente leitura e escrita por um nó
  resources: # recursos do PVC
    requests: # solicitação de recursos
      storage: 1Gi # tamanho do volume que ele vai solicitar
  storageClassName: nfs # nome da classe de armazenamento que será utilizada
  selector: # seletor de labels
    matchLabels: # labels que serão utilizadas para selecionar o PV
      storage: nfs # label que será utilizada para selecionar o PV
#vim pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
      volumeMounts:
        - name: meu-pvc
          mountPath: /usr/share/nginx/html
  volumes:
    - name: meu-pvc
      persistentVolumeClaim:
        claimName: meu-pvc

#    volumeMounts: # montando o volume no container
#    - name: meu-pvc  # nome do volume
#      mountPath: /usr/share/nginx/html # caminho onde o volume será montado no container
#  volumes: # definindo o volume que será utilizado pelo Pod
#  - name: meu-pvc # nome do volume
#    persistentVolumeClaim: # tipo de volume, no caso, um PersistentVolumeClaim
#      claimName: meu-pvc # nome do PVC

# echo "<h1>GIROPOPS STRIGUS GIRUS</h1>" > /mnt/data/index.html
#kubectl exec -it nginx-pod -- ls /usr/share/nginx/html
#kubectl exec -it nginx-pod -- curl localhost
