apiVersion: v1
kind: Pod
metadata:
  name: goproxy-desafio-day4
  labels:
    app: goproxy
spec:
  containers:
  - name: goproxy
    image: registry.k8s.io/goproxy:0.1
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 8080
    readinessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 15
      periodSeconds: 10
    livenessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 15
      periodSeconds: 10
    # startupProbe:
    #   tcpSocket:
    #     port: 8080
    #   # httpGet:
    #   #   path: /
    #   #   port: liveness-port
    #   failureThreshold: 30
    #   periodSeconds: 10
