#echo -n 'giropops' | base64
#echo -n 'Z2lyb3BvcHM=' | base64 -d
#kubectl get secret giropops-secret -o yaml
#kubectl create secret generic giropops-secret --from-literal=username=<SEGREDO> --from-literal=password=giropops
#--from-file e --from-env-file
#kubectl exec giropops-pod -- env

apiVersion: v1
kind: Secret
metadata:
  name: giropops-secret
type: Opaque
data: # Inicio dos dados
  username: SmVmZXJzb25fbGluZG8=
  password: Z2lyb3BvcHM=
---
apiVersion: v1
kind: Pod
metadata:
  name: giropops-pod
spec:
  containers:
    - name: giropops-container
      image: nginx
      resources:
        limits:
          cpu: "500m"
          memory: "512Mi"
        requests:
          cpu: "100m"
          memory: "128Mi"
      env: # Inicio da definição das variáveis de ambiente
        - name: USERNAME # Nome da variável de ambiente que será usada no Pod
          valueFrom: # Inicio da definição de onde o valor da variável de ambiente será buscado
            secretKeyRef: # Inicio da definição de que o valor da variável de ambiente será buscado em um Secret, através de uma chave
              name: giropops-secret # Nome do Secret que contém o valor da variável de ambiente que será usada no Pod
              key: username # Nome da chave do campo do Secret que contém o valor da variável de ambiente que será usada no Pod
        - name: PASSWORD # Nome da variável de ambiente que será usada no Pod
          valueFrom: # Inicio da definição de onde o valor da variável de ambiente será buscado
            secretKeyRef: # Inicio da definição de que o valor da variável de ambiente será buscado em um Secret, através de uma chave
              name: giropops-secret # Nome do Secret que contém o valor da variável de ambiente que será usada no Pod
              key: password # Nome da chave do campo do Secret que contém o valor da variável de ambiente que será usada no Pod
