#base64 ~/.docker/config.json / base64 -i /Users/care1/.docker/config.json

apiVersion: v1
kind: Secret
metadata:
  name: docker-hub-secret # nome do Secret
type: kubernetes.io/dockerconfigjson # tipo do Secret, neste caso é um Secret que armazena credenciais Docker
data:
  .dockerconfigjson: | # substitua este valor pelo conteúdo do seu arquivo config.json codificado em base64
    ewoJImF1dGhzIjoge30sCgkiY3JlZHNTdG9yZSI6ICJkZXNrdG9wIiwKCSJjdXJyZW50Q29udGV4dCI6ICJkZXNrdG9wLWxpbnV4IiwKCSJwbHVnaW5zIjogewoJCSIteC1jbGktaGludHMiOiB7CgkJCSJlbmFibGVkIjogInRydWUiCgkJfQoJfSwKCSJmZWF0dXJlcyI6IHsKCQkiaG9va3MiOiAidHJ1ZSIKCX0KfQ==
---
apiVersion: v1
kind: Pod
metadata:
  name: meu-pod-docker-hub
spec:
  containers:
    - name: meu-container-docker-hub
      image: alpine # imagem privada do Docker Hub
  imagePullSecrets: # campo que define o Secret que armazena as credenciais do Docker Hub
    - name: docker-hub-secret # nome do Secret
