apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: isr-letsencrypt-issuer-prod
spec:
  acme:
    server: https://acme-production-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: isr-issuer-account-key-prod
    solvers:
    - http01:
        ingress:
          ingressClassName: nginx
